// ============================================================
// ResinOps — Nav module registry
// src/lib/modules.js
//
// Lives outside App.jsx (which renders the sidebar from this list) so
// FacilitySettings.jsx can also import it for the module visibility
// toggle UI without creating a circular import between the two.
//
// `tier` drives src/lib/moduleVisibility.js's isModuleVisible():
//   "core"       — always visible, not toggleable
//   "home"       — visible on both product tiers by default
//   "commercial" — hidden by default on a "home" product tier
// ============================================================

export const MODULES = [
  // ── Operations Hub ──────────────────────────────────────────────────────────
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "🏠",
    available: true,
    description: "Today's alerts, action items & facility-wide overview",
    isScheduler: true,
    tier: "core",
    sectionBreak: "Operations Hub",
  },
  {
    id: "ai-assistant",
    label: "AI Assistant",
    icon: "✨",
    available: true,
    description: "Cannabis operations expert — cultivation, extraction, compliance",
    isScheduler: false,
    tier: "core",
  },
  {
    id: "ops-analyst",
    label: "AI Operations Analyst",
    icon: "🧠",
    available: true,
    description: "Ask plain-English questions about your facility data — harvests, revenue, compliance, strain performance",
    isScheduler: true,
    tier: "core",
    sectionBreak: null,
  },
  // ── Cultivation ─────────────────────────────────────────────────────────────
  {
    id: "grow-map",
    label: "Grow Map",
    icon: "🗺️",
    available: true,
    description: "Persistent room & space repository — all facility grow areas, statuses, and reset timing",
    isScheduler: true,
    tier: "home",
    sectionBreak: "Cultivation",
  },
  {
    id: "scheduler",
    label: "Grow Scheduler",
    icon: "📅",
    available: true,
    description: "Plan cultivation timelines from clone cut through harvest to inventory",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "clone-scheduler",
    label: "Clone Scheduler",
    icon: "✂️",
    available: true,
    description: "Back-calculates clone cut dates from harvest dates, room reset time, and veg lead",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "mother-plants",
    label: "Mother Plant Manager",
    icon: "🌿",
    available: true,
    description: "Track mother plants by strain, cycle timing, projected cuts, and clone scheduling",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "harvest",
    label: "Harvest Batches",
    icon: "🌿",
    available: true,
    description: "Post-harvest tracking — drying, trimming, curing, and graded final weights per strain",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "strain-db",
    label: "Strain Database",
    icon: "🧬",
    available: true,
    description: "Strain registry with parentage, aggregated cultivation & processing data, and AI descriptions",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "pheno-hunt",
    label: "Pheno Hunt Tracker",
    icon: "🔭",
    available: true,
    description: "Seed-by-seed tracking from pop to keeper selection with scoring and COA data",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "tc-tracker",
    label: "TC Tracker",
    icon: "🧪",
    available: true,
    description: "Tissue culture vessel tracking — explant to transfer, contamination logging",
    isScheduler: true,
    tier: "home",
  },
  // ── Processing ──────────────────────────────────────────────────────────────
  {
    id: "production",
    label: "Production Scheduler",
    icon: "🏭",
    available: true,
    description: "Track every production batch from intake to live inventory",
    isScheduler: true,
    tier: "commercial",
    sectionBreak: "Processing",
  },
  {
    id: "yield-dashboard",
    label: "Yield Dashboard",
    icon: "📊",
    available: true,
    description: "Cultivation and extraction yield per strain, segmented by Fresh Frozen / Dry Bud / Dry Trim input material",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "remediation",
    label: "Remediation Calculator",
    icon: "☢️",
    available: true,
    description: "Radiation dose calculator for yeast/mold and Aspergillus remediation after failed lab tests",
    isScheduler: true,
    tier: "commercial",
  },
  // ── Compliance ──────────────────────────────────────────────────────────────
  {
    id: "gmp-hub",
    label: "GMP Hub",
    icon: "📋",
    available: true,
    description: "SOP library, deviation register, shift log, step sign-offs, and digital batch records",
    isScheduler: true,
    tier: "commercial",
    sectionBreak: "Compliance",
  },
  {
    id: "qc-testing",
    label: "QC & Lab Testing",
    icon: "🔬",
    available: true,
    description: "Full COA panel tracking — failed microbial tests auto-flag to Remediation and hold Sales",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "cult-inputs",
    label: "Cultivation Inputs",
    icon: "🌱",
    available: true,
    description: "Nutrients, amendments, and beneficial insect releases — regulatory-grade documentation",
    isScheduler: true,
    tier: "home",
  },
  {
    id: "spray-log",
    label: "Pesticide Log",
    icon: "🛡️",
    available: true,
    description: "Regulatory pesticide application records — EPA reg #, REI, PHI, licensed applicator, weather conditions",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "ipm-tracker",
    label: "IPM Tracker",
    icon: "🐛",
    available: true,
    description: "Pest scouting, beneficial releases, and IPM scheduling — linked to upcoming production batches",
    isScheduler: true,
    tier: "home",
  },
  // ── People & Labor ──────────────────────────────────────────────────────────
  {
    id: "labor-dash",
    label: "Labor Dashboard",
    icon: "📊",
    available: true,
    description: "Daily labor demand vs capacity — production batches + cultivation harvest events",
    isScheduler: true,
    tier: "commercial",
    sectionBreak: "People & Labor",
  },
  {
    id: "employees",
    label: "Employees",
    icon: "👥",
    available: true,
    description: "Staff profiles, pesticide licenses, GMP certifications, and training records",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "labor-setup",
    label: "Labor Setup",
    icon: "⚙️",
    available: true,
    description: "Define facility shift structure and labor types with hourly rates",
    isScheduler: true,
    tier: "commercial",
  },
  // ── Business ────────────────────────────────────────────────────────────────
  {
    id: "inventory",
    label: "Inventory",
    icon: "📦",
    available: true,
    description: "Items, vendors, purchase orders, and stock management",
    isScheduler: true,
    tier: "commercial",
    sectionBreak: "Business",
  },
  {
    id: "sales",
    label: "Sales & Pre-Orders",
    icon: "🧾",
    available: true,
    description: "Track sellable inventory against the production schedule and manage holds",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "customers",
    label: "Customers",
    icon: "🏢",
    available: true,
    description: "Dispensary/wholesale accounts, contact info, pipeline stage, and order history",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "finance",
    label: "Cost & P&L",
    icon: "💰",
    available: true,
    description: "COGS per batch · 280E-structured · SKU pricing · Bill of materials",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "batch-dashboard",
    label: "Batch Margin Dashboard",
    icon: "📈",
    available: true,
    description: "Estimated revenue, COGS, and gross margin across all production batches",
    isScheduler: true,
    tier: "commercial",
  },
  // ── Facility ────────────────────────────────────────────────────────────────
  {
    id: "maintenance",
    label: "Maintenance & Facilities",
    icon: "🏗️",
    available: true,
    description: "Work orders, downtime tracking, and lockout/tagout safety log",
    isScheduler: true,
    tier: "commercial",
    sectionBreak: "Facility",
  },
  {
    id: "equipment",
    label: "Equipment Registry",
    icon: "🔧",
    available: true,
    description: "Company-wide asset list with PM schedules, warranty, and service history",
    isScheduler: true,
    tier: "commercial",
  },
  {
    id: "facility-map",
    label: "Facility Map",
    icon: "🏭",
    available: true,
    description: "Processing, dry/cure, storage & office spaces — cleaning logs and batch assignment",
    isScheduler: true,
    tier: "commercial",
  },
  // ── Settings (pinned separately at the bottom of the sidebar, not in the
  // main accordion — see App.jsx's hardcoded ["data-manager",
  // "facility-settings","metrc"] render block) ────────────────────────────────
  {
    id: "data-manager",
    label: "Data & Imports",
    icon: "📥",
    available: true,
    description: "AI-powered universal import, data backup, and restore — onboard any facility in minutes",
    isScheduler: true,
    tier: "core",
  },
  {
    id: "facility-settings",
    label: "Facility Settings",
    icon: "🏢",
    available: true,
    description: "Facility identity — appears on all exports, batch records, and spray logs",
    isScheduler: true,
    tier: "core",
  },
  {
    id: "metrc",
    label: "METRC Sync",
    icon: "🌿",
    available: true,
    description: "Sync plants, harvests, packages, and lab results from METRC",
    isScheduler: true,
    tier: "commercial",
  },
];

// Every distinct sectionBreak name, in first-seen order — used as the
// "start fully collapsed" default for the sidebar accordion on a
// facility's first-ever visit (nothing in localStorage yet).
export const ALL_SECTION_NAMES = [...new Set(MODULES.map(m => m.sectionBreak).filter(Boolean))];
